
; Generated by AutoGUI 2.5.7
#SingleInstance Force
#NoEnv
SetWorkingDir %A_ScriptDir%
SetBatchLines -1

global g_ID


f12::
WinGet, g_ID, ID, A 
Gui Destroy ;正常切換頁簽
Gui Add, Button, x216 y8 w114 h41 gButtonClose, 關閉
Gui Add, Tab3, x16 y72 w314 h287, 常用符號|系統資訊
Gui Tab, 1
Gui Add, Button, x32 y112 w80 h54 gButton, 電腦
Gui Add, Button, x128 y112 w80 h54 gButton, ❤
Gui Add, Button, x224 y112 w80 h54 gButton, ✅
Gui Add, Button, x32 y176 w80 h54 gButton, 1️⃣2️⃣3️⃣
Gui Add, Button, x128 y176 w80 h54 gButton, 電腦
Gui Add, Button, x224 y176 w80 h54 gButton, 電腦
Gui Tab, 2
Gui Add, Button, x40 y120 w112 h45 gButtonToday, 本日日期
Gui Tab

Gui Show, w360 h422, Window
Return

Button:
  WinActivate, ahk_id %g_ID%
  Send %A_GuiControl%
  Return
  
ButtonClose:
  gui hide
  Return  

ButtonToday:
  WinActivate, ahk_id %g_ID%
  Send %A_YYYY%年%A_MM%月%A_DD%日
  Return

GuiEscape:
GuiClose:
    ExitApp