#NoEnv  ; Recommended for performance and compatibility with future AutoHotkey releases.
; #Warn  ; Enable warnings to assist with detecting common errors.
SendMode Input  ; Recommended for new scripts due to its superior speed and reliability.
SetWorkingDir %A_ScriptDir%  ; Ensures a consistent starting directory.

; 彈出選擇視窗，選擇後傳出ErrorLevel
#SingleInstance Force

; Y/N/Cancel=3, 問號圖示=32, 預設按鈕2=256.
; 3+32+256=291
MsgBox, 291,, 是否繼續執行? (點擊 是 或 否)
IfMsgBox Yes 
{
    MsgBox You pressed Yes.
    ;ExitApp, 1
} 
else IfMsgBox No 
{
    MsgBox You pressed No.
    ;ExitApp, 2
}    
Else
{
    ;ExitApp, 3
}

; Generated by AutoGUI 2.6.2
#SingleInstance Force
#NoEnv
SetWorkingDir %A_ScriptDir%
SetBatchLines -1

Gui Add, Text, x26 y43 w118 h0 +0x200, Text
Gui Add, Text, x16 y16 w156 h35 +0x200, 請選擇要執行的應用程式
Gui Add, Button, gbtnWord x16 y80 w80 h23, &1 Word
Gui Add, Button, gbtnExcel x120 y80 w80 h23, &2 Excel
Gui Add, Button, gbtnNotepad x224 y80 w80 h23, &3 Notepad

Gui Show, w344 h148, Window
Return

btnWord(CtrlHwnd, GuiEvent, EventInfo, ErrLevel := "") {
  ;Run "C:\Program Files\Microsoft Office\root\Office16\WINWORD.EXE"
  ExitApp, 1
}

btnExcel:
  ;Run Excel
  ExitApp, 2
Return

btnNotepad:
  ;Run Notepad
  ExitApp 3
Return

GuiEscape:
GuiClose:
  ExitApp